appName: ""
replicas: 1
containerName: ""
listeningPort: 80
ports: []
# Example:
# ports:
#   - name: http
#     port: 80
#     targetPort: 8080
#     containerPort: 8080
#     protocol: TCP
#   - name: metrics
#     port: 9090
#     targetPort: 9090
#     containerPort: 9090
#     protocol: TCP

image:
  repository: ""
  tag: "latest"
  pullPolicy: "Always"

imagePullSecrets:
  enabled: false
  secrets: []

env: []
envFrom: []
command: []
args: []
# Example:
# args:
#   - --hostname=https://auth.pausegarra.es
#   - --http-enabled=true

resources: {}

livenessProbe:
  path: /healthz
  # Optional. If empty, deployment template falls back to:
  # 1) first .Values.ports[] using: containerPort > targetPort > port
  # 2) .Values.listeningPort
  port: null

rollingUpdate:
  enabled: true

configMap:
  enabled: false
  values: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

traefikMiddlewareRedirectRegex:
  enabled: false
  items: []
  redirectIngress:
    enabled: true
    className: ""
    annotations: {}
    serviceName: dummy-svc
    servicePort: 80
    hosts: []
    # hosts:
    #   - host: pausegarra.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    tls: []
  # Example:
  # items:
  #   - name: redirect-com-to-es-root-only
  #     namespace: infra
  #     regex: ^https?://pausegarra\.com(/.*)?$
  #     replacement: https://pausegarra.es${1}
  #     permanent: true
  #   - name: redirect-blog-com-to-es
  #     namespace: infra
  #     regex: ^https?://blog\.pausegarra\.com(/.*)?$
  #     replacement: https://blog.pausegarra.es${1}
  #     permanent: true
